Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 10, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 11, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
/bin/sh: python3: command not found
/bin/sh: python3: command not found
/bin/sh: python3: command not found
/bin/sh: python3: command not found
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 11, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 11, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 11, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 11, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 11, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 11, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 11, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 13, in <module>
    import app1
ModuleNotFoundError: No module named 'app1'
2021년 12월 7일 9시 51분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 223, in <module>
    send_message()
  File "/home/ec2-user/bot/bot.py", line 121, in send_message
    kakao_friends_update()
  File "/home/ec2-user/bot/bot.py", line 196, in kakao_friends_update
    with open("kakao_code_friends_owner.json","r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'kakao_code_friends_owner.json'
2021년 12월 7일 9시 52분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
friends_update fail
1
1
1
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 223, in <module>
    send_message()
  File "/home/ec2-user/bot/bot.py", line 137, in send_message
    kakao_friends_send(message, user_uuid)
  File "/home/ec2-user/bot/bot.py", line 59, in kakao_friends_send
    with open("kakao_code_friends_owner.json","r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'kakao_code_friends_owner.json'
2021년 12월 7일 9시 53분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
friends_update fail
1
1
1
{'access_token': 'dnhSbnXELMzNgL1pEc2qIPm8zQIbFp5raRlcYAorDNQAAAF9klEBEA', 'token_type': 'bearer', 'refresh_token': 'hM1JRNakFAMFwruGiMxF3-7xo1wshMU8QYBoTgorDNQAAAF9klEBDw', 'expires_in': 21599, 'scope': 'account_email profile_image talk_message profile_nickname friends', 'refresh_token_expires_in': 5183999}
token check finish
-----------message------------
12월 07일의 이천시 날씨는 
최고온도 12도 
최저온도 0도 입니다.
오전 강수확률은 30%이며 
오후 강수확률은 20%입니다.
코로나바이러스감염증-19 국내 발생현황 (12.07. 00시 기준)
확진자 수는 4954명입니다.
------------------------------
임낙균에게 알림 전송완료
0
2021년 12월 7일 10시 0분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
friends_update fail
2021년 12월 7일 11시 0분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
friends_update fail
2021년 12월 7일 12시 1분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
friends_update fail
2021년 12월 7일 13시 1분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
friends_update fail
{'access_token': 'dnhSbnXELMzNgL1pEc2qIPm8zQIbFp5raRlcYAorDNQAAAF9klEBEA', 'token_type': 'bearer', 'refresh_token': 'hM1JRNakFAMFwruGiMxF3-7xo1wshMU8QYBoTgorDNQAAAF9klEBDw', 'expires_in': 21599, 'scope': 'account_email profile_image talk_message profile_nickname friends', 'refresh_token_expires_in': 5183999}
token check finish
-----------message------------
12월 07일의 강남구 날씨는 
최고온도 12도 
최저온도 2도 입니다.
오전 강수확률은 30%이며 
오후 강수확률은 20%입니다.
코로나바이러스감염증-19 국내 발생현황 (12.07. 00시 기준)
확진자 수는 4954명입니다.
------------------------------
준성에게 알림 전송완료
2021년 12월 7일 14시 1분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
friends_update fail
{'access_token': 'dnhSbnXELMzNgL1pEc2qIPm8zQIbFp5raRlcYAorDNQAAAF9klEBEA', 'token_type': 'bearer', 'refresh_token': 'hM1JRNakFAMFwruGiMxF3-7xo1wshMU8QYBoTgorDNQAAAF9klEBDw', 'expires_in': 21599, 'scope': 'account_email profile_image talk_message profile_nickname friends', 'refresh_token_expires_in': 5183999}
token check finish
-----------message------------
12월 07일의 구로구 날씨는 
최고온도 13도 
최저온도 1도 입니다.
오전 강수확률은 30%이며 
오후 강수확률은 20%입니다.
코로나바이러스감염증-19 국내 발생현황 (12.07. 00시 기준)
확진자 수는 4954명입니다.
------------------------------
황선희에게 알림 전송완료
2021년 12월 7일 15시 1분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
friends_update fail
2021년 12월 7일 16시 1분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"msg":"this access token is already expired","code":-401}
kakao_owner_check_finish
friends_update fail
2021년 12월 7일 17시 1분
code를 입력하세요.
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 223, in <module>
    code = input()
EOFError: EOF when reading a line
  File "/home/ec2-user/bot/bot.py", line 56
    flag = 1
       ^
IndentationError: expected an indented block
2021년 12월 7일 19시 1분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
김동옥success
김민정success
성훈success
연아success
이정은success
임낙균success
제훈success
준성success
황선아success
황선희success
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 233, in <module>
    send_message()
  File "/home/ec2-user/bot/bot.py", line 135, in send_message
    user_content = i['content']
KeyError: 'content'
2021년 12월 7일 20시 1분
{"msg":"Forbidden","code":-403}
kakao_owner_token_finish
{"id":1932291041,"connected_at":"2021-10-01T05:04:23Z","properties":{"nickname":"황도규","profile_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_640x640.jpg","thumbnail_image":"http://k.kakaocdn.net/dn/Ic7cO/btrfFGlVj6E/i8E055Zaa30KvjZrqOupjK/img_110x110.jpg"},"kakao_account":{"profile_nickname_needs_agreement":false,"profile_image_needs_agreement":false,"profile":{"nickname":"황도규","thumbnail_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_110x110.jpg","profile_image_url":"http://k.kakaocdn.net/dn/copNUC/btrmcY0PWcs/xmtM5JRpMxQPXWDKbAwagk/img_640x640.jpg","is_default_image":false},"has_email":true,"email_needs_agreement":false,"is_email_valid":true,"is_email_verified":true,"email":"hello2263@naver.com"}}
kakao_owner_check_finish
김동옥success
김민정success
성훈success
연아success
이정은success
임낙균success
제훈success
준성success
황선아success
황선희success
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 246, in <module>
    send_message()
  File "/home/ec2-user/bot/bot.py", line 135, in send_message
    user_content = i['content']
KeyError: 'content'
2021년 12월 7일 21시 1분
2021년 12월 7일 22시 0분
friends_update success
2021년 12월 7일 23시 0분
friends_update success
2021년 12월 8일 0시 0분
friends_update fail
2021년 12월 8일 1시 0분
friends_update fail
2021년 12월 8일 2시 0분
friends_update fail
2021년 12월 8일 3시 0분
friends_update fail
2021년 12월 8일 4시 0분
friends_update fail
2021년 12월 8일 5시 0분
friends_update fail
2021년 12월 8일 6시 0분
friends_update fail
2021년 12월 8일 7시 0분
friends_update fail
2021년 12월 8일 8시 0분
friends_update fail
token check finish
-----------message------------
12월 08일 관악구의 
최고온도 11도 
최저온도 1도 입니다.
오전 강수확률은 0%이며 
오후 강수확률은 20%입니다.
코로나바이러스감염증-19 국내 발생현황 (12.07. 00시 기준)
확진자 수는 4954명입니다.
------------------------------
김민정에게 알림 전송완료
2021년 12월 8일 9시 0분
friends_update fail
2021년 12월 8일 10시 0분
friends_update success
2021년 12월 8일 11시 0분
friends_update success
2021년 12월 8일 12시 0분
friends_update success
2021년 12월 8일 13시 0분
friends_update success
2021년 12월 8일 14시 0분
friends_update success
2021년 12월 8일 15시 0분
friends_update success
2021년 12월 8일 16시 0분
friends_update success
2021년 12월 8일 17시 0분
friends_update fail
2021년 12월 8일 18시 0분
friends_update fail
2021년 12월 8일 19시 0분
friends_update fail
2021년 12월 8일 20시 0분
friends_update fail
2021년 12월 8일 21시 0분
friends_update fail
2021년 12월 8일 22시 0분
friends_update fail
2021년 12월 8일 23시 0분
friends_update fail
2021년 12월 9일 0시 0분
friends_update fail
2021년 12월 9일 1시 0분
friends_update fail
2021년 12월 9일 2시 0분
friends_update fail
2021년 12월 9일 3시 0분
friends_update fail
2021년 12월 9일 4시 0분
friends_update fail
2021년 12월 9일 5시 0분
friends_update fail
2021년 12월 9일 6시 0분
friends_update fail
2021년 12월 9일 7시 0분
friends_update fail
2021년 12월 9일 8시 0분
friends_update fail
2021년 12월 9일 9시 0분
friends_update fail
token check finish
-----------message------------
12월 09일 관악구의 
최고온도 10도 
최저온도 2도 입니다.
오전 강수확률은 20%이며 
오후 강수확률은 30%입니다.
코로나바이러스감염증-19 국내 발생현황 (12.08. 00시 기준)
확진자 수는 7175명입니다.
------------------------------
김민정에게 알림 전송완료
2021년 12월 9일 10시 0분
friends_update fail
2021년 12월 9일 11시 0분
friends_update fail
2021년 12월 9일 12시 0분
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 268, in <module>
    kakao_to_friends_get_refreshtokens()
  File "/home/ec2-user/bot/bot.py", line 155, in kakao_to_friends_get_refreshtokens
    refresh = token_data['refresh_token']
KeyError: 'refresh_token'
2021년 12월 9일 13시 0분
yODb-aNSxIRAYF29Gx2_kwvpGdYCxUCVZneb4oFyMrjoV3ihfCUzAPKUOLbChHtcatW4gwopb9QAAAF9nTsAcg
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 256, in <module>
    func.kakao_to_friends_get_refreshtokens()
  File "/home/ec2-user/bot/func.py", line 42, in kakao_to_friends_get_refreshtokens
    with open("kakao_code_friends_owner.json","r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'kakao_code_friends_owner.json'
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 169, in <module>
    func.nowtime()
  File "/home/ec2-user/bot/func.py", line 93, in nowtime
    now = datetime.now()
NameError: name 'datetime' is not defined
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 169, in <module>
    func.nowtime()
  File "/home/ec2-user/bot/func.py", line 93, in nowtime
    now = datetime.now()
NameError: name 'datetime' is not defined
2021년 12월 9일 16시 0분
5QYsfRHBrcMHGze6V_xCMkZ4uV7l6jsSFtsY4XPZNHjoYTH140RyLPblp-JE3i8UGlIw3wo9dRoAAAF9nfySAA
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 181, in <module>
    func.kakao_to_friends_get_refreshtokens()
  File "/home/ec2-user/bot/func.py", line 47, in kakao_to_friends_get_refreshtokens
    with open("kakao_code_friends_owner.json","r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'kakao_code_friends_owner.json'
2021년 12월 9일 18시 0분
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 177, in <module>
    for i in data:
  File "/usr/local/lib64/python3.7/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib64/python3.7/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 502, in _check_session_support
    None)
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 220, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: 172.17.0.2:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 61b1c5936b1ab12acf11575a, topology_type: Single, servers: [<ServerDescription ('172.17.0.2', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.17.0.2:27017: timed out')>]>
2021년 12월 9일 19시 0분
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 177, in <module>
    for i in data:
  File "/usr/local/lib64/python3.7/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib64/python3.7/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 502, in _check_session_support
    None)
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 220, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: 172.17.0.2:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 61b1d3a2ab70539e2537000b, topology_type: Single, servers: [<ServerDescription ('172.17.0.2', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.17.0.2:27017: timed out')>]>
2021년 12월 9일 20시 0분
Traceback (most recent call last):
  File "/home/ec2-user/bot/bot.py", line 177, in <module>
    for i in data:
  File "/usr/local/lib64/python3.7/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib64/python3.7/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 502, in _check_session_support
    None)
  File "/usr/local/lib64/python3.7/site-packages/pymongo/topology.py", line 220, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: 172.17.0.2:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 61b1e1b2e3efaa2215be1632, topology_type: Single, servers: [<ServerDescription ('172.17.0.2', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.17.0.2:27017: timed out')>]>
